### ISSUE TITLE
No build tasks in Rakefile.rb

### ISSUE THREAD

**Issue by whyer** [haf/logirel#18]
Using logirel (0.1.6) from gem install. 
After running logirel in a directory i get a rakefile without the actual build tasks. 

```
Create common assembly info file? [Yn]Y
Add msbuild task for sln file? [Yn]Y
      append  Rakefile.rb
```

``````
require "rubygems"
require "bundler"
Bundler.setup
$: << './'

require 'albacore'
require 'rake/clean'
require 'semver'

require 'buildscripts/utils'
require 'buildscripts/paths'
require 'buildscripts/project_details'
require 'buildscripts/environment'

# to get the current version of the project, type 'SemVer.find.to_s' in this rake file.
task :default  => ["env:release"]```
``````

**Comment by haf** [comment]
This is a known issue if you answer no to a certain question in the CLI.

Aiming to fix this with the tsort of tasks; help is really appreciated here.

**Comment by whyer** [comment]
I answer Yes on everything! Workaround?
I can not build the package locally either: 
    bundle install
    rake build

gives me: 
    ERROR:  While executing gem ... (Gem::InvalidSpecificationException)
    ["vendor/cache/albacore-0.2.7.gem", "vendor/cache/diff-lcs-1.1.2.gem", "vendor/cache/rubyzip-0.9.4.gem"] are not fil
es

**Comment by haf** [comment]
Remove gemfile.lock to fix the error you wrote about and try again. You shouldn't be getting that.

Try this branch I just pushed to:
https://github.com/haf/logirel/tree/develop

**Comment by whyer** [comment]
Ok. Got it to build and run locally now. Got other errors, I see it is work in progress. I will try and fix and do a pull request.
(I see that you removed the "files" list from cli.rb. But it is used in path.tt)
